# This will show the time on a 2nd line
# Add a "\" at the end of an item, if you want the next item to show on the same line
format = """
$username\
$hostname\
$time\
$all\
$directory
$character
"""

[character]
success_symbol = '[❯❯❯❯](#37f499 bold)'
error_symbol = '[XXXX](#f16c75 bold)'
vicmd_symbol = '[❮❮❮❮](#a48cf2 bold)'

[battery]
disabled = true

[gcloud]
disabled = true

[time]
style = '#a48cf2 bold'
disabled = false
format = '[\[$time\]]($style) '
# https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html
# %T	00:34:60	Hour-minute-second format. Same to %H:%M:%S.
# time_format = '%y/%m/%d %T'
time_format = '%y/%m/%d'


[username]
style_user = '#a48cf2 bold'
style_root = 'white bold'
format = '[$user]($style) '
show_always = true

[hostname]
ssh_only = true
format = '(white bold)[$hostname](#37f499 bold)'

[directory]
style = '#04d1f9 bold'
truncation_length = 0
truncate_to_repo = false

[nodejs]
symbol = ""
format = '[ ( ) ]()'

[ruby]
detect_variables = []
detect_files = ['Gemfile', '.ruby-version']

[golang]
symbol = ""
format = '[ ( ) ]()'
detect_files = ["go.mod"]

[java]
symbol = " "
format = '[[ ( ) ]]()'

